Aktualisierung Dokumentation für die neue Expressionsyntax
TVTower/Documentation pull request #29
Opened 2024-10-30 11:30 UTC by nittka

2024-10-30 11:32 UTC, nittka commented
Eine erste Überarbeitung der Hauptdateien ist erfolgt. Die eigentliche Beschreibung der Variablen und Expressions sowie der script-Syntax für die Verfügbarkeit muss noch gemacht werden.

2024-10-30 12:25 UTC, GWRon commented on database_de/lang.md
> +## Eigenschaften von role
Eventuell sollten wir das mit "programmeroles" (aus den Datenbanken) synchronisieren - also auch "programmeroles" nennen"?

2024-10-30 12:27 UTC, GWRon commented on database_de/main.md
> +In zukünfitgen Versionen wird das alte Format nicht mehr unterstützt werden und eigene Datenbank-Dateien müssen auf das neue Format umgestellt werden.
zukünfitgen
zukünftigen

In zukünfitgen Versionen wird das alte Format nicht mehr unterstützt werden und eigene Datenbank-Dateien müssen auf das neue Format umgestellt werden.
-> erstes werden wenigstens rausnehmen
Zukünftige Versionen unterstützen das alte Format nicht mehr und eigene Datenbank-Dateien müssen auf das neue Format umgestellt werden.

2024-10-30 12:28 UTC, GWRon commented on database_de/main.md
> +Der `titel`-Knoten enthält Titel von Drehbuchvorlagen, Filmen etc.
titel -> title

2024-10-30 12:30 UTC, GWRon commented on database_de/news.md
> +Die angestoßenen Nachrichten selbst dürfen keine eigenen Variablendefinitionen enthalten.
Ist dem so? Ich dachte da gibt es einen "merge"-Teil im Code?

2024-10-30 13:18 UTC, nittka commented on database_de/lang.md
> +## Eigenschaften von role
Da bin ich relativ emotionslos. Die Datenbankdateien zwischen verschiedenen Versionen auszutauschen ist ohnehin gefährlich, hier hätte es aber auch die Auswirkung, dass selbst bei alten Spielständen wirklich auf die aktuelle Datenbank zugegriffen wird und nicht die im Spielstand enthaltene.

2024-10-30 13:23 UTC, nittka commented on database_de/news.md
> +Die angestoßenen Nachrichten selbst dürfen keine eigenen Variablendefinitionen enthalten.
Ja, best effort. Wenn alles zusammenpasst funktioniert der Merge. Im schlimmsten Fall wird eine Exception geworfen. Ich habe den Text etwas entschärft.

2024-11-01 16:13 UTC, nittka commented
Ich bin heute bei der Expression-Beschreibung gut vorangekommen. Im Prinzip fehlen noch die globalen Zugriffe auf Personen/Programme, die kontextabhängigen Zugriffe (Attribute des eigenen Drehbuchs etc) und die Scripte für die Verfügbarkeit.

Ich denke aber, dass man das nicht in aller Ausführlichkeit machen muss, da ich keine weitverbreiteten Anwendungsfälle für viele der nun möglichen Zugriffe sehe.

2024-11-02 16:18 UTC, GWRon requested changes

2024-11-02 16:18 UTC, GWRon commented on database_de/variables.md
> +Hier nur ein paar Beispiel.
Beispiel_e

2024-11-02 16:18 UTC, GWRon commented on database_de/variables.md
> +In `game.gamescriptexpression.bmx` kann man nachschauen, ob vielleicht benötigte Information schon jetzt verfügbar ist.
ob _die_ vielleicht benötigte Information

2024-11-02 16:18 UTC, GWRon commented on database_de/variables.md
> +* `${.person:"836b4aa3-b5c6-4529-b30d-4501594cdf13":"nickname"}` - Spitzname der Person mit der gegebenen ID
an sich ist das hier die GUID ... die ID kennt man an der Stelle nicht (kann aber bspweise code-intern bekannt sein - fuer codetechnisch erzeugte Skripte (warum auch immer) bzw wenn man die ID in einer Variable abgespeichert haben sollte.

2024-11-02 16:18 UTC, GWRon commented on database_de/variables.md
> +* `${.programme:"04439fd1-e89f-4922-a48e-6f8ddf96f7ab":"episodecount"}` - Anzahl der Folgen der Serie
das erste "der" kann weg - oder?

2024-11-02 16:18 UTC, GWRon commented on database_de/variables.md
> +* `${.programme:"02d0dfa5-dbcf-40b5-abb4-7e20a58d8efa":"cast":1:"fullname"}` - vollständiger Name der Besetzung mit Index 1
hier vielleicht einfach noch den Hinweis "(erster Cast hat den Index 0)" hinzufuegen?

2024-11-02 16:18 UTC, GWRon commented on database_de/variables.md
> +* `${.role:"1d1f05ea-43ff-4399-81d9-f00239460700":"fullname"}` - vollständiger Name der Rolla
Roll_e

2024-11-02 16:39 UTC, nittka commented on database_de/news.md
> +Wenn die Variablendefinitionen der aktuellen und der Vorgängernachricht nicht zusammen passen, kann es zum Programmabruch kommen.
Ja, wenn's nicht passt und mergen nötig wäre, wird eine Exception geworfen. Das finde ich für den Text aber zu technisch. Auf der sicheren Seite ist man mit der Definition in der Startnachricht.

2024-11-17 14:22 UTC, nittka commented
If there are no further objections, I'd update the documentation to that state.
The editor update site has been updated to support the new expression syntax. Some basic validation is implemented.

2024-11-17 14:38 UTC, GWRon approved these changes

2024-11-17 14:38 UTC, GWRon commented on database_de/variables.md
> +* Der Anwalt und seine turen Liebschaften
turen teuren

2024-11-17 14:38 UTC, GWRon commented on database_de/variables.md
> +Einstiegspunkte für die definierten Funktionen sind `game.gamescriptexpression.bmx` für TVTower-spezifische Funktionen und `base.util.scriptexpression_ng.bmx` für allgemeine Funktionen (Bediungen etc
Bediungen Bedingungen

2024-11-17 14:38 UTC, GWRon commented on database_de/variables.md
> +Es ist nicht direkt möglich, eine Person zu erzeugen und dann auf die unterschiedlichen Namensbestandteile (Vorname, Nachname, Titel) zuzugreifen.
Titel - vielleicht Hinweis einbauen, dass damit "Dr." oder "Prof." gemeint ist.

2024-11-17 14:38 UTC, GWRon commented on database_de/variables.md
> +Die Funktion `.local` bietet kontextunabhängigen Zugriff auf die Übersetzungsdateien (`res/lang/...`).
.local .locale

2024-11-17 14:38 UTC, GWRon commented on database_de/variables.md
> +* `${.if:${.gt:${.worldtime:"hour"}:21}:"spät":"nicht spät"} - Wenn es nach 22 Uhr ist, kommt "spät" raus, ansonsten "nicht spät"
da fehlt nach `spät"}` noch das Hochkomma.

2024-11-17 14:38 UTC, GWRon commented on database_de/variables.md
> +Da die Verwendung spizter Klammern in XML außer für Tags nicht wirklich empfehlenswert ist, wird von der Verwendung der normalen Operatoren (`<`,`<=`,`>`, `>=`,`<>`) abgeraten.
spizter spitzer

2024-11-17 14:38 UTC, GWRon commented on database_de/variables.md
> +Mit `${.not:bedingung}` kein eine Bedingung negiert werden.
kein kann

2024-11-17 14:38 UTC, GWRon commented on database_de/variables.md
> +* `${.and:p1:p2}` - wahr gdw alle Bedinungen (p1 und p2) wahr sind
Bedinungen Bedingungen

2024-11-17 14:38 UTC, GWRon commented on database_de/variables.md
> +* `${.and:p1:p2:p3:p4}` - wahr gdw alle Bedinungen (p1 bis p4) wahr sind
Bedinungen Bedingungen

2024-11-17 14:38 UTC, GWRon commented on database_de/variables.md
> +* `${.or:p1:p2}` - wahr gdw mindestens eine der Bediungenen (p1 oder p2) wahr sind
Bediungenen Bedingungen

2024-11-17 14:38 UTC, GWRon commented on database_de/variables.md
> +Mit Funktionen gibt es nun eine zusättliche Möglichkeit, die zu einer besseren Lesbarkeit in der Datenbank führen kann.
zusättliche zusätzliche

2024-11-17 14:40 UTC, GWRon commented
Rechtschreibfehler vlt noch korrigieren, ansonsten passt es meiner Meinung nach. Gut gemacht.

2024-11-17 19:13 UTC, nittka commented
Danke für die Rückmeldung. Ich habe die Änderungen eingearbeitet und lokal auf den Master gebracht.

2024-11-17 19:13 UTC, closed without merging